In [19]:
#Normal indexing and Slicing 

import numpy as np

a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [14]:
a[1,2]

np.int64(5)

In [15]:
a[1:3,1:3]

array([[4, 5],
       [7, 8]])

In [20]:
#Fancy Indexing 

a[[0,2,3]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [21]:
a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [ ]:
# Boolean Indexing

import numpy as np
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[85, 44, 46, 46],
       [98, 18, 54, 86],
       [74, 76, 47, 51],
       [89, 31, 95, 82],
       [48, 22, 42, 62],
       [82, 27, 30, 47]], dtype=int32)

In [ ]:
# find all numbers greater than 50

#a > 50
a[a > 50]

array([85, 98, 54, 86, 74, 76, 51, 89, 95, 82, 62, 82], dtype=int32)

In [35]:
#find out a evan numbers 
a[a  % 2 == 0 ]

array([44, 46, 46, 98, 18, 54, 86, 74, 76, 82, 48, 22, 42, 62, 82, 30],
      dtype=int32)

In [40]:
#find all number greater than 50 in even 

a [(a > 50) & (a % 2 == 0)]


array([98, 54, 86, 74, 76, 82, 62, 82], dtype=int32)

In [43]:
#find all numbers not divisible by 7
a[~(a % 7 == 0)]

array([85, 44, 46, 46, 18, 54, 86, 74, 76, 47, 51, 89, 31, 95, 82, 48, 22,
       62, 82, 27, 30, 47], dtype=int32)