In [9]:
import numpy as np

a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[100.,  64.,  58.],
       [ 85.,  58.,  61.],
       [  7.,  14.,  59.]])

In [11]:
#max/min/sum/product
#  0->cols and 1-> row

#np.max(a1)
np.min(a1,axis=0)
#np.sum(a1)
#np.prod(a1)


array([ 7., 14., 58.])

In [13]:
#mean/median/std/var

np.mean(a1,axis=1)

array([74.        , 68.        , 26.66666667])

In [14]:
#trignometry 
np.sin(a1)

array([[-0.50636564,  0.92002604,  0.99287265],
       [-0.17607562,  0.99287265, -0.96611777],
       [ 0.6569866 ,  0.99060736,  0.63673801]])

In [20]:
#dot product

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)



array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
#log and exponents

np.log(a1)
np.exp(a1)

array([[2.68811714e+43, 6.23514908e+27, 1.54553894e+25],
       [8.22301271e+36, 1.54553894e+25, 3.10429794e+26],
       [1.09663316e+03, 1.20260428e+06, 4.20121040e+25]])

In [28]:
#round / floor / ceil

np.ceil(np.random.random((2,3))*100)

array([[22., 77., 22.],
       [48., 23., 89.]])