In [5]:

import numpy as np
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [7]:
#scalar Oprations
#arithmatic oprator 

a2 * 2


array([[24, 26, 28, 30],
       [32, 34, 36, 38],
       [40, 42, 44, 46]])

In [8]:
#relational oprater
a2 == 14

array([[False, False,  True, False],
       [False, False, False, False],
       [False, False, False, False]])

In [9]:
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])