In [1]:
import numpy as np

In [2]:
arr = np.array([12,4,5,6,])
arr

array([12,  4,  5,  6])

In [3]:
a = [12,3,6,6]
a

[12, 3, 6, 6]

Vectors and Matrix 

In [6]:
a = [[1,2,3],[2,3,4],[4,5,5]]
a

np.array(a)

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 5]])

In [ ]:
# Array Genration Function

arr = np.arange(1,12)
arr 


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
arr = np.zeros((4,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [14]:
arr = np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
#Random Genration Function
np.random.rand(10)

array([0.98105749, 0.0990862 , 0.34420264, 0.34684977, 0.51973057,
       0.47090968, 0.16396476, 0.33234662, 0.75634291, 0.93158849])

Creating Numpy Arrayy

In [1]:
import numpy as np


a = np.array([15,5,6,6])
a


array([15,  5,  6,  6])

In [4]:
#2D array 
b = np.array([[12,3,6,],[4,5,6]])
print(b)

[[12  3  6]
 [ 4  5  6]]


In [5]:
c = np.array([1,2,3],dtype=bool)
c

array([ True,  True,  True])

In [7]:
#With Arrange

np.arange(1,22,3)


array([ 1,  4,  7, 10, 13, 16, 19])

In [24]:
# with reshape

np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [ ]:
#np.ones and np.zeros

np.ones((3,4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
#random

np.random.random((3,4))

array([[0.07309226, 0.04942441, 0.77879084, 0.49111777],
       [0.03704408, 0.44968341, 0.57252152, 0.48261094],
       [0.2861991 , 0.09257455, 0.37530669, 0.30845895]])

In [17]:
#np.linespace

np.linspace(-10,16)

array([-10.        ,  -9.46938776,  -8.93877551,  -8.40816327,
        -7.87755102,  -7.34693878,  -6.81632653,  -6.28571429,
        -5.75510204,  -5.2244898 ,  -4.69387755,  -4.16326531,
        -3.63265306,  -3.10204082,  -2.57142857,  -2.04081633,
        -1.51020408,  -0.97959184,  -0.44897959,   0.08163265,
         0.6122449 ,   1.14285714,   1.67346939,   2.20408163,
         2.73469388,   3.26530612,   3.79591837,   4.32653061,
         4.85714286,   5.3877551 ,   5.91836735,   6.44897959,
         6.97959184,   7.51020408,   8.04081633,   8.57142857,
         9.10204082,   9.63265306,  10.16326531,  10.69387755,
        11.2244898 ,  11.75510204,  12.28571429,  12.81632653,
        13.34693878,  13.87755102,  14.40816327,  14.93877551,
        15.46938776,  16.        ])

In [18]:
#identity

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])