broadcasting's
=================
Broadcasting is a powerful mechanism that allows NumPy to perform operations on arrays of different shapes and sizes. 

It enables you to apply operations to arrays without explicitly reshaping them, making your code more concise and efficient.

In [1]:
#same shape
import numpy as np

a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)


print(a)
print(b)

print(a  + b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]


In [8]:
import numpy as np

a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

print(a)
print(b)

print(a + b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


Broadcasting Rules.

Rule 1: Same Number of Dimensions

If two arrays have different dimensions, NumPy adds 1 to the left side of the smaller array’s shape.

2. Make each dimension of the two arrays the same size.
   • If the sizes of each dimension of the two arrays do not match, dimensions with size 1 are stretched to the size of the other array.
   
   • If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.

In [10]:
import numpy as np
a = np.array([1, 2, 3])      # shape = (3,)
b = np.array([[1], [2], [3]]) # shape = (3,1)


print(a)
print(b)
print(a + b)

[1 2 3]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [12]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

print(a)
print(b)

print(a+b)

[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [13]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)

print(a)
print(b)

print(a+b)

[[0 1 2]]
[[0]
 [1]
 [2]
 [3]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [14]:
a = np.array([1])
b = np.arange(4).reshape(2,2)

print(a)
print(b)

print(a+b)

[1]
[[0 1]
 [2 3]]
[[1 2]
 [3 4]]


In [16]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)

print(a)
print(b)
#print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
