Indexing And Slicing

In [7]:
import numpy as np

a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2) 

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
a2[1,0]

np.int64(4)

In [15]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [16]:
a3[1,0,1]

np.int64(5)

In [17]:
a3[0,1,0]

np.int64(2)

In [19]:
a3[0,0,0]

np.int64(0)

In [23]:
a3[1,1,0]

np.int64(6)

Slicing

In [24]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
a1[2:5]

array([2, 3, 4])

In [26]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
a2[0,:]

array([0, 1, 2, 3])

In [28]:
a2[:,2]

array([ 2,  6, 10])

In [29]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [30]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [40]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [55]:
a2[1,::3]

array([4, 7])

In [54]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [58]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [61]:
a3[0,1,:]

array([3, 4, 5])

In [62]:
a3[1,:,1]

array([10, 13, 16])

In [63]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [65]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])